name: RareItemHunter
main: com.minecraftfunpark.rareitemhunter.RareItemHunter
version: '1.7'
database: false
softdepend: [RemoteEntities]
description: Rare Item Hunter
commands:
    ri:
      description: RareItems commands
permissions: 
# All
  rareitemhunter.*:
    description: All RareItemHunter permissions
    default: op
    children:
      rareitemhunter.hunter.compass: true
      rareitemhunter.hunter.hatch: true
      rareitemhunter.hunter.craft: true
      rareitemhunter.admin.spawnpoint: true
      rareitemhunter.admin.egg: true
      rareitemhunter.admin.boss: true
      rareitemhunter.admin.reload: true
      rareitemhunter.admin.notify: true
      rareitemhunter.admin.essence: true
      rareitemhunter.admin.compass: true
      rareitemhunter.admin.crafter: true
 # Hunter
  rareitemhunter.hunter.*:
    description: Access to hunting permissions
    default: true
    children:
      rareitemhunter.hunter.compass: true
      rareitemhunter.hunter.hatch: true
      rareitemhunter.hunter.craft: true
  rareitemhunter.hunter.craft:
    description: Craft rare item components and rare items from rare essences
    default: false
  rareitemhunter.hunter.compass:
    description: Use a legendary compass to find bosses
    default: false
  rareitemhunter.hunter.hatch:
    description: Awaken bosses
    default: false
# Admin
  rareitemhunter.admin.*:
    description: All admin permissions
    default: false
    children:
      rareitemhunter.admin.spawnpoint: true
      rareitemhunter.admin.egg: true
      rareitemhunter.admin.boss: true
      rareitemhunter.admin.reload: true
      rareitemhunter.admin.notify: true
      rareitemhunter.admin.essence: true
      rareitemhunter.admin.compass: true
      rareitemhunter.admin.crafter: true
  rareitemhunter.admin.spawnpoint:
    description: Manage boss egg spawn points
    default: false
  rareitemhunter.admin.egg:
    description: Spawn boss eggs
    default: false
  rareitemhunter.admin.boss:
    description: Spawn bosses
    default: false
  rareitemhunter.admin.reload:
    description: Reload the plugin
    default: false
  rareitemhunter.admin.notify:
    description: Notified of issues/statuses/updates
    default: false
  rareitemhunter.admin.essence:
    description: Give out rare essences
    default: false
  rareitemhunter.admin.compass:
    description: Give out legendary compasses
    default: false
  rareitemhunter.admin.crafter:
    description: Can create essences via commands
    default: false